# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bfe5b76a3362d07019735c354048882370bf9dc70f2c1526f8bb6537ed95c0dc4c8a50056cc27dbcba09699c625118b0d9f10687e7c60ab462681a1c64c0d62f

test:
  secret_key_base: 7d9ae19eab8576b6a779d485ad69487b13cf1c099e1a3166d6bf00c9e838486cbb97307981904dbabb6adec718c41c1facaf4015ad3cd63361287c3364259e3a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
